# Generated by Django 3.1.7 on 2021-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootsShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Classic', 'Classic'), ('High Tops', 'High Tops'), ('Boots', 'Boots')], max_length=40),
        ),
    ]
